### ISSUE TITLE
Seems like urls in posts are not handled

### ISSUE THREAD

**Issue by progressionnetwork** [Kisspeace/accless-tg-scraper#3]
If we want to extract text from a post containing links, it appears that TgMessageEntityUrl may not be functioning as expected.
O modified it like:
```
class TgMessageEntityUrl(TgMessageEntity):
    """Message entity with text and url behind the text.
    """
    def __init__(self, offset: int = 0, length: int = 0, url: str = '', text: str = ''):
        TgMessageEntity.__init__(self, offset, length)
        self.text: text
        self.url: url
```
and
```
 elif subject.name == 'a': # Hyperlink or user mention.
            res = TgMessageEntityUrl()
            res.url = subject['href']
            res.text = subject.contents[0]
```
But it still not working well. Were else should I modify code?

**Comment by Kisspeace** [comment]
Hi, could you provide me with some links to the Telegram posts where the problems appear?

**Comment by progressionnetwork** [comment]
Hi, try for example https://t.me/cryptonews/3888. It will detect all links as text 'link'. But as I see, for markdown it should extract link like a [link](https://twitter.com/WuBlockchain/status/1700504956414099601) ?

**Comment by Kisspeace** [comment]
You can try now

**Comment by progressionnetwork** [comment]
Just tried. Seems like the result is not changed. Let me describe in details:
When in author's telegram channel post used text with link (href) then your parser handle it as text but not as link. 
Better if it will handle like a [text_of_link](link_from_href).

**Comment by Kisspeace** [comment]
##### Example for https://t.me/cryptonews/3888:
```python
import asyncio
from accless_tg_scraper.parser import *
from accless_tg_scraper.client import *
from accless_tg_scraper.classes import *
from accless_tg_scraper.serialize.markdown import *

async def main():
    telegram = TgScraper()
    post = await telegram.get_post('cryptonews', 3888)
    # md_text is a content converted to markdown, like on a web page.
    # Using dump_content function from accless_tg_scraper.serialize.classes
    md_text = dump_content(post.content, post.entities, RULE_SET_MD)
    print(md_text)
if __name__ == '__main__':
    asyncio.run(main())
```
#### md_text will be:
Someone created fake news that BlackRock plans to acquire Voyager Digital to pump tokens. The Associated Press website even published it with paid content. The social media source marked in the press release is a Chinese account with only one fan. VGX has gained 8% in the last 24 hours. [— link](https://twitter.com/WuBlockchain/status/1700504956414099601)

**Comment by progressionnetwork** [comment]
Now links parsing works like a charm! thank you 🙏
